# nginx/nginx.conf
events {
worker_connections 1024; # Maximum number of connections per process
}

http {
    # Sets the bounding box
    limit_req_zone $binary_remote_addr zone=apilimit:10m rate=10r/s;  # Limit requests to 10 per second per IP address

    map $http_x_experiment_group $backend_pool {
        debug api-v2;
        default api-v1;
    }

    upstream api-v1 {
        server api-v1:8000; # Backend service name and port
    }

    upstream api-v2 {
        server api-v2:8000; # Backend service name and port
    }
# Defining our virtual server
    server {
        listen 80;          
        server_name localhost; # Domain name or IP that this server block manages
        # Redirects all HTTP requests to HTTPS
        return 301 https://$host$request_uri; 
    }
    server {
        listen 443 ssl; # Listen on port 443 for HTTPS
        server_name localhost; # Domain name or IP that this server block manages

        # SSL configuration
        ssl_certificate /etc/nginx/certs/nginx.crt; # Path to the SSL certificate
        ssl_certificate_key /etc/nginx/certs/nginx.key; # Path to the SSL certificate key    

        ssl_protocols TLSv1.2 TLSv1.3; # Supported SSL protocols
        ssl_ciphers HIGH:!aNULL:!MD5; # Supported SSL ciphers
        ssl_prefer_server_ciphers on; # Prefer server ciphers over client ciphers

        location /nginx_status {
            stub_status on; # Activates the module stub_status
            access_log off; # Do not log access to this endpoint
            allow 127.0.0.1; # Allow access only from localhost (export it)
            allow 172.28.0.0/16; # Or from the Docker network
            deny all; # Blocks all other access
        }

# All requests that start with /predict/ will be handled here
        location /predict {
            auth_basic "API Access Protected"; # Message displayed to the user
            auth_basic_user_file /etc/nginx/.htpasswd; # Path to the .htpasswd file in the container

            limit_req zone=apilimit burst=5 nodelay; # Apply rate limiting to this location

            proxy_pass http://$backend_pool;            
            # proxy_pass: Redirects the request to the backend service
            # http://$backend_pool '$backend_pool' is the name of our API's pool.

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}